core
dirs
dotfiles
# ssh-github
# git-https

rust
golang
node
bun
python
lua
zig
ocaml
cpp

fzf
dunst
# dunst-git
wob
# wob-git
fuzzel
# fuzzel-git
rot8-git
light
# light-git
fd-find
# fd-find-git
ripgrep
# ripgrep-git

neovim
opencode
llama

1password
zen
alacritty
# alacritty-git
thunderbird
