core
dirs
dotfiles

ssh-config
# git-https

lua
node
python
cpp
# rust
# golang
# zig
# ocaml

fzf
ripgrep
# dunst
# wob
# fuzzel
# light

neovim
# llama
# opencode

# 1password
# zen
# alacritty
# alacritty-git
# thunderbird
