#---SYSTEM---
core
dotfiles
#ssh-config

#---LANGUAGES---
golang
node
#rust
zig
#lua

#---APPLICATIONS---
#1password
#brave
#thunderbird
#
#alacritty
#alacritty-git

#---TOOLS---
#fzf
#ripgrep
#neovim
#tree-sitter
#stylua
#llama
#
#niri
