# docker build -t devenv-test -f Dockerfile.fedora .
# docker run --rm -it devenv-test

FROM fedora:latest

RUN dnf install -y git curl wget

RUN useradd -m -s /bin/bash user && echo "user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/user

ENV DEV_ENV=/home/user/devenv
ENV HOME=/home/user

USER user

WORKDIR /home/user/devenv
COPY . .

CMD ["/bin/bash"]
