# Usage: docker build -t devenv-test-ubuntu -f Dockerfile.ubuntu .
# docker run --rm -it devenv-test-ubuntu

FROM ubuntu:latest

RUN apt-get update && apt-get install -y sudo git curl wget

RUN mkdir -p /etc/sudoers.d && useradd -m -s /bin/bash user && echo "user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/user

ENV DEV_ENV=/home/user/devenv
ENV HOME=/home/user

USER user

WORKDIR /home/user/devenv
COPY . .

CMD ["/bin/bash"]
