#!/usr/bin/env bash

set -euo pipefail

case "$OS" in
    fedora) sudo dnf install -y alacritty ;;
    ubuntu)
        sudo add-apt-repository ppa:aslatter/ppa -y
        sudo apt-get install -y alacritty
        ;;
esac
