#!/usr/bin/env bash

set -euo pipefail

if command -v brave-browser &>/dev/null; then
    exit 0
fi

case "$OS" in
    fedora)
        sudo dnf install dnf-plugins-core
        sudo dnf config-manager addrepo --from-repofile=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
        sudo dnf install brave-browser
        ;;
    ubuntu)
        sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        sudo curl -fsSLo /etc/apt/sources.list.d/brave-browser-release.sources https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
        sudo apt update
        sudo apt install brave-browser
        ;;
esac
