#!/usr/bin/env bash

set -euo pipefail

case "$OS" in
    fedora)
        sudo dnf install -y \
            gcc-c++ ninja-build \
            git curl wget moreutils make cmake \
            desktop-file-utils parallel tmux jq \
            stow
        ;;
    ubuntu)
        sudo apt-get install -y \
            gcc-c++ ninja-build \
            git curl wget moreutils make cmake \
            desktop-file-utils parallel tmux jq \
            stow
        ;;
esac
