#!/usr/bin/env bash

set -euo pipefail

case "$OS" in
    fedora) sudo dnf install -y gcc gcc-c++ clang clang-tools-extra ;;
    ubuntu) sudo apt-get install -y g++ clangd clang-format clang-tidy ;;
esac

pip3 install cpplint
