#!/usr/bin/env bash

set -euo pipefail

FILES=`find "$DEV_ENV/home" -maxdepth 1 -type f`
for f in "${FILES[@]}"; do
    base=`basename "$f"`
    home_path="$HOME/$base"
    if [[ -f "$home_path" && ! -L "$home_path" ]]; then
        echo "  Backing up $home_path"
        mv "$home_path" "$home_path.bak"
    fi
done

cd "$DEV_ENV"
stow -v --target="$HOME" home

echo "Dotfiles setup complete!"
