#!/usr/bin/env bash

set -euo pipefail

mkdir -p "$HOME/.config"
mkdir -p "$HOME/.local/share/fonts"

cd "$DEV_ENV"
stow -D -v --target="$HOME" home
stow -v --no-folding --target="$HOME" home

echo "Dotfiles setup complete!"
