#!/usr/bin/env bash

set -euo pipefail

if command -v fd &>/dev/null; then
    exit 0
fi

GIT_DIR="$HOME/git"

mkdir -p "$GIT_DIR"

if [[ ! -d "$GIT_DIR/fd/.git" ]]; then
    git clone git@github.com:sharkdp/fd.git "$GIT_DIR/fd"
fi

cd "$GIT_DIR/fd"
git fetch
git checkout cb3fad48bb2d366080efa421d8499ec968f60a6c

cargo install --path .
