#!/usr/bin/env bash

set -euo pipefail

if command -v fdfind &>/dev/null || command -v fd &>/dev/null; then
    exit 0
fi

case "$OS" in
    fedora) sudo dnf install -y fd-find ;;
    ubuntu) sudo apt install -y fd-find ;;
esac
