#!/usr/bin/env bash

set -euo pipefail

if command -v fzf &>/dev/null; then
    exit 0
fi

if [[ ! -d "$CODEDIR/fzf/.git" ]]; then
    git clone https://github.com/junegunn/fzf "$CODEDIR/fzf"
fi

cd "$CODEDIR/fzf"
git fetch
git checkout v0.70.0

./install --bin

ln -sf "$CODEDIR/fzf/bin/fzf" "$BINDIR/fzf"
