#!/usr/bin/env bash
set -euo pipefail

config_file="$HOME/.gitconfig"
urls=("github.com" "gitlab.com" "codeberg.org")

for url in "${urls[@]}"; do
    if ! git config --file "$config_file" --get url."https://${url}/".insteadOf >/dev/null; then
        git config --file "$config_file" url."https://${url}/".insteadOf git@${url}:
    fi
done
