#!/usr/bin/env bash
set -euo pipefail

if ! command -v go &>/dev/null; then
    gobase="go1.26.1.linux-amd64"
    gotar="${gobase}.tar.gz"
    wget https://go.dev/dl/${gotar} -O /tmp/${gotar}
    if ! echo "031f088e5d955bab8657ede27ad4e3bc5b7c1ba281f05f245bcc304f327c987a  /tmp/${gotar}" | sha256sum -c --status; then
        echo "wrong sha256sum"
        exit 1
    fi
    tar xf /tmp/${gotar} -C ~/.local/
fi

if ! command -v gopls &>/dev/null; then
    go install golang.org/x/tools/gopls@latest
fi
