#!/usr/bin/env bash

set -euo pipefail

if command -v go &>/dev/null; then
    exit 0
fi

ver="1.26.1"
base="go"
asset="go${ver}.linux-amd64.tar.gz"

cd $TMPDIR
curl -fsSL -O https://go.dev/dl/${asset}
tar -xf ${asset}
mv ${base} ~/.local/go
