#!/usr/bin/env bash

set -euo pipefail

if ! command -v go &>/dev/null; then
    gobase="go1.26.1.linux-amd64"
    gotar="${gobase}.tar.gz"
    wget https://go.dev/dl/${gotar} -O ${TMPDIR}/${gotar}
    tar xf ${TMPDIR}/${gotar} -C ~/.local/
fi

if ! command -v gopls &>/dev/null; then
    go install golang.org/x/tools/gopls@latest
fi
