#!/usr/bin/env bash

set -euo pipefail

case "$OS" in
    fedora) sudo dnf install -y vulkan-devel glslc spirv-headers-devel ;;
    ubuntu) sudo apt-get install -y libvulkan-dev shaderc spirv-headers glslang-tools ;;
esac

if command -v llama &>/dev/null; then
    exit 0
fi

if [[ ! -d "$CODEDIR/llama.cpp/.git" ]]; then
    git clone https://github.com/ggerganov/llama.cpp "$CODEDIR/llama.cpp"
fi

cd "$CODEDIR/llama.cpp"
cmake -B build -DBUILD_SHARED_LIBS=OFF -DGGML_VULKAN=ON
cmake --build build --config Release -j
sudo cmake --install build
