#!/usr/bin/env bash

set -euo pipefail

if command -v lua &>/dev/null && command -v luarocks &>/dev/null; then
    exit 0
fi

case "$OS" in
    fedora) sudo dnf install -y lua5.1 luarocks libstdc++-static ;;
    ubuntu) sudo apt-get install -y lua5.1 luarocks libstdc++-12-dev ;;
esac
