#!/usr/bin/env bash

set -euo pipefail

if command -v nvim &>/dev/null; then
    exit 0
fi

GIT_DIR="$HOME/git"
PROJECTS_DIR="$HOME/projects"

mkdir -p "$GIT_DIR"

if [[ ! -d "$GIT_DIR/neovim/.git" ]]; then
    git clone https://github.com/neovim/neovim.git "$GIT_DIR/neovim"
fi

cd "$GIT_DIR/neovim"

make CMAKE_BUILD_TYPE=Release
sudo make install

nvim --version

PLUGIN_DIR="$HOME/.config/nvim/pack/vendor/start/quickfill.nvim"

mkdir -p "$PROJECTS_DIR"

if [[ ! -d "$PROJECTS_DIR/quickfill.nvim/.git" ]]; then
    git clone git@github.com:davkk/quickfill.nvim.git "$PROJECTS_DIR/quickfill.nvim"
fi

cd "$PROJECTS_DIR/quickfill.nvim"
git pull

mkdir -p "$(dirname "$PLUGIN_DIR")"
[[ -L "$PLUGIN_DIR" ]] && rm "$PLUGIN_DIR"
[[ -d "$PLUGIN_DIR" ]] && rm -rf "$PLUGIN_DIR"
ln -sf "$PROJECTS_DIR/quickfill.nvim" "$PLUGIN_DIR"
