#!/usr/bin/env bash

set -euo pipefail

if [[ ! -d "$CODEDIR/neovim/.git" ]]; then
    git clone https://github.com/neovim/neovim "$CODEDIR/neovim"
fi

cd "$CODEDIR/neovim"

git pull
make distclean
make CMAKE_BUILD_TYPE=Release -j
sudo chown -R "$(id -u):$(id -g)" "$CODEDIR/neovim"
sudo make install

if [[ ! -d "$CODEDIR/quickfill.nvim" ]]; then
    PLUGIN_DIR="$HOME/.local/share/nvim/site/pack/local/start"
    mkdir -p "$PLUGIN_DIR"
    git clone https://github.com/davkk/quickfill.nvim "$CODEDIR/quickfill.nvim"
    ln -fs "$CODEDIR/quickfill.nvim" "$PLUGIN_DIR"
fi
