#!/usr/bin/env bash

set -euo pipefail

GIT_DIR="$HOME/git"
PROJECTS_DIR="$HOME/projects"

mkdir -p "$GIT_DIR"

if [[ ! -d "$GIT_DIR/neovim/.git" ]]; then
    git clone git@github.com:neovim/neovim.git "$GIT_DIR/neovim"
fi

cd "$GIT_DIR/neovim"

git pull
make CMAKE_BUILD_TYPE=Release -j10
sudo make install

PLUGIN_DIR="$HOME/.local/share/nvim/site/pack/local/start"
mkdir -p "$PLUGIN_DIR"

if [[ ! -d "$PROJECTS_DIR/quickfill.nvim" ]]; then
    git clone git@github.com:davkk/quickfill.nvim.git "$PROJECTS_DIR/quickfill.nvim"
fi

ln -fs "$PROJECTS_DIR/quickfill.nvim" "$PLUGIN_DIR"

if ! command -v tree-sitter > /dev/null 2>&1; then
    mkdir -p /tmp/tree-sitter
    wget https://github.com/tree-sitter/tree-sitter/releases/download/v0.24.7/tree-sitter-linux-x64.gz -O /tmp/tree-sitter/tree-sitter.gz
    gzip -d /tmp/tree-sitter/tree-sitter.gz -f
    mv /tmp/tree-sitter/tree-sitter ~/.local/bin/tree-sitter
    chmod +x ~/.local/bin/tree-sitter
fi
