#!/usr/bin/env bash

set -euo pipefail

if ! command -v volta &>/dev/null; then
    tmp_dir="${TMPDIR}/volta"
    mkdir -p "$tmp_dir"
    wget "https://github.com/volta-cli/volta/releases/download/v2.0.2/volta-2.0.2-linux.tar.gz" -O "$tmp_dir/volta.tar.gz"
    tar xf "$tmp_dir/volta.tar.gz" -C "$tmp_dir"
    mv "$tmp_dir/volta" ~/.local/bin/
    mv "$tmp_dir/volta-migrate" ~/.local/bin/
    mv "$tmp_dir/volta-shim" ~/.local/bin/
    rm -rf "$tmp_dir"
fi

export VOLTA_HOME="$HOME/.local/volta"
export PATH="$PATH:$VOLTA_HOME/bin"

if ! command -v node &>/dev/null; then
    volta install node
fi

for pkg in typescript-language-server prettier eslint_d; do
    if ! command -v "$pkg" &>/dev/null; then
        npm install -g "$pkg"
    fi
done
