#!/usr/bin/env bash

set -euo pipefail

if command -v node &>/dev/null && command -v npm &>/dev/null; then
    exit 0
fi

BINDIR=$HOME/.local/bin
OPTDIR=$HOME/.local/node

ver="v24.20.0"
base="node-${ver}-linux-x64"
asset="${base}.tar.xz"

cd $TMPDIR
curl -fsSL -O https://nodejs.org/dist/${ver}/${asset}
tar -xf ${asset}
mv ${base} $OPTDIR

for file in bin/*; do
    ln -s $OPTDIR/$file $BINDIR
done

for pkg in prettier eslint_d; do
    if ! command -v "$pkg" &>/dev/null; then
        npm install -g "$pkg"
    fi
done
