#!/usr/bin/env bash

set -euo pipefail

case "$OS" in
    fedora) sudo dnf install -y opam ;;
    ubuntu) sudo apt-get install -y opam ;;
esac

export OPAMROOT="$HOME/.local/opam"
opam init --disable-sandboxing --yes 2>/dev/null || true
