#!/usr/bin/env bash

set -euo pipefail

if [[ ! -f "$HOME/.config/pip/pip.conf" ]]; then
    mkdir -p "$HOME/.config/pip"
    cat << HERE > "$HOME/.config/pip/pip.conf"
[global]
break-system-packages = true
HERE
fi

if ! command -v python3 &>/dev/null && ! command -v python &>/dev/null || ! command -v pip3 &>/dev/null; then
    case "$OS" in
        fedora) sudo dnf install -y python3 python3-pip ;;
        ubuntu) sudo apt-get install -y python3 python3-pip ;;
    esac
fi

if ! command -v uv &>/dev/null; then
    pip3 install uv==0.10.9
fi

for pkg in basedpyright ruff; do
    if ! command -v "$pkg" &>/dev/null; then
        pip3 install "$pkg"
    fi
done
