#!/usr/bin/env bash

set -euo pipefail

case "$OS" in
    fedora) sudo dnf install -y python3 python3-pip ;;
    ubuntu) sudo apt install -y python3 python3-pip ;;
esac

if ! command -v uv &>/dev/null; then
    pip3 install uv==0.10.9
fi

if [[ ! -d "$HOME/.local/share/python" ]]; then
    uv python install
fi

for pkg in basedpyright ruff black flake8; do
    if ! command -v "$pkg" &>/dev/null; then
        pip3 install "$pkg"
    fi
done
