#!/usr/bin/env bash

set -euo pipefail

if command -v rg &>/dev/null; then
    exit 0
fi

GIT_DIR="$HOME/git"

mkdir -p "$GIT_DIR"

if [[ ! -d "$GIT_DIR/ripgrep/.git" ]]; then
    git clone git@github.com:BurntSushi/ripgrep.git "$GIT_DIR/ripgrep"
fi

cd "$GIT_DIR/ripgrep"
git fetch
git checkout 4519153e5e461527f4bca45b042fff45c4ec6fb9

cargo install --path .

rg --version
