#!/usr/bin/env bash

set -euo pipefail

if command -v cargo &>/dev/null; then
    exit 0
fi

ver="1.94.0"
base="rust-${ver}-x86_64-unknown-linux-gnu"
asset="${base}.tar.xz"

cd $TMPDIR
curl -fsSL -O https://static.rust-lang.org/dist/${asset}
tar -xf ${asset}
./${base}/install.sh --prefix=$HOME/.local/rust
