#!/usr/bin/env bash

set -euo pipefail

if command -v cargo &>/dev/null; then
    exit 0
fi

export PATH="$HOME/.local/rust/bin:$HOME/.local/cargo/bin:$PATH"

rustbase="rust-1.94.0-x86_64-unknown-linux-gnu"
rusttar="${rustbase}.tar.xz"

wget https://static.rust-lang.org/dist/${rusttar} -O ${TMPDIR}/${rusttar}

mkdir -p ${TMPDIR}/${rustbase}
tar xf ${{TMPDIR}}/${rusttar} -C ${{TMPDIR}}
${TMPDIR}/${rustbase}/install.sh --prefix=$HOME/.local/rust
