#!/usr/bin/env bash

set -euo pipefail

if command -v thunderbird &>/dev/null; then
    exit 0
fi

case "$OS" in
    fedora) sudo dnf install -y thunderbird ;;
    ubuntu) sudo apt install -y thunderbird ;;
esac
