#!/usr/bin/env bash

set -euo pipefail

if command -v wob &>/dev/null; then
    exit 0
fi

GIT_DIR="$HOME/git"

case "$OS" in
    fedora) sudo dnf install -y wayland-devel meson ninja-build inih-devel wayland-protocols-devel libseccomp-devel ;;
    ubuntu) sudo apt install -y libwayland-dev meson ninja-build libinih-dev wayland-protocols libseccomp-dev ;;
esac

mkdir -p "$GIT_DIR"

if [[ ! -d "$GIT_DIR/wob/.git" ]]; then
    git clone git@github.com:francma/wob.git "$GIT_DIR/wob"
fi

cd "$GIT_DIR/wob"
git fetch
git checkout b712016926e8a9f803e0de4d48a7412dc9374538

meson build
ninja -C build
sudo ninja -C build install

wob --help | head -1
