#!/usr/bin/env bash

set -euo pipefail

if command -v zig &>/dev/null; then
    exit 0
fi

export ZVM_HOME="$HOME/.local/zvm"
export PATH="$ZVM_HOME/bin:$PATH"

go install -ldflags "-s -w" github.com/tristanisham/zvm@latest

zvm install master
zvm use master
zvm install --zls master
