#!/usr/bin/env bash

set -euo pipefail

if ! command -v zig &>/dev/null && ! command -v zvm &>/dev/null; then
    go install -ldflags "-s -w" github.com/tristanisham/zvm@latest

    zvm install master
    zvm use master
    zvm install --zls master
fi
