#!/usr/bin/env bash

set -euo pipefail

if command -v zig &>/dev/null; then
    exit 0
fi

ver="0.16.0"
base="zig-x86_64-linux-${ver}"
asset="${base}.tar.xz"

cd $TMPDIR
curl -fsSL -O "https://ziglang.org/download/${ver}/${asset}"
tar -xf ${asset}
mv ${base} ${OPTDIR}/zig
ln -s ${OPTDIR}/zig/zig ${BINDIR}
