set -g default-terminal "tmux-256color"
set -ag terminal-features ",xterm-256color:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g status-style "fg=green,bg=default"
set -sg escape-time 0
set -g allow-passthrough on
set -g detach-on-destroy off

set-option -g history-limit 5000

set -g extended-keys on
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle

bind -T copy-mode-vi C-h resize-pane -L 3
bind -T copy-mode-vi C-j resize-pane -D 3
bind -T copy-mode-vi C-k resize-pane -U 3
bind -T copy-mode-vi C-l resize-pane -R 3
